
/*
 *  Copyright (C) 2008 TU Delft. All rights reserved.
 *
 *  This module reads a mesh generated by Gmsh and stores it in globdat
 *  as NodeSet and ElementSet object.
 *
 *  NodeGroups can be specified in the input file.
 *
 *  This Module does not define any constraints!
 *
 *  Frans van der Meer, August 2008 
 *
 *  Changelog:
 *
 *  Modified: Luiz Ant. T. Mororo, l.a.taumaturgomororo@tudelft.nl
 *  Date:     July 2019
 * 
 *  The class has been changed in order to enable parallel computing.
 *  Master ElementSet and NodeSet pointers are stored in order to be in
 *  several Models and Modules.
 *
 *  Modified: Luiz A. T. Mororo, luiz.mororo@ifce.edu.br
 *  Date: Fev 2025
 *
 *  Clean-up code, remove parallel functionalities, and refactored member 
 *  functions for better performance, storage scheme, and to meet new 
 *  Jem/Jive (version 3.0) data types, for instance, `idx_t'. 
 */

 
#ifndef GMSH_INPUT_MODULE_H
#define GMSH_INPUT_MODULE_H


#include <jive/app/Module.h>
#include <jive/fem/XElementSet.h>
#include <jive/fem/XNodeSet.h>
#include <jive/util/Assignable.h>


using jem::idx_t;
using jem::Ref;
using jem::String;


using jem::util::Properties;


using jive::IntVector;


using jive::app::Module;
using jive::fem::XElementSet;
using jive::fem::XNodeSet;
using jive::util::Assignable;


//=======================================================================
//   class GmshInputModule 
//=======================================================================


class GmshInputModule : public Module
{
 public:

  JEM_DECLARE_CLASS       ( GmshInputModule, Module );

  static const char*        TYPE_NAME;

  static const char*        FILE_NAME_PROP;
  static const char*        DIM_PROP;
  static const char*        EL_GRP_IDX_PROP;
  static const char*        STG_MODE_PROP;


  explicit                  GmshInputModule 

    ( const String&           name = "gmshInput" );

  virtual Status            init

    ( const Properties&       conf,
      const Properties&       props,
      const Properties&       globdat )                    override;
      
  static Ref<Module>        makeNew

    ( const String&           name,
      const Properties&       conf,
      const Properties&       props,
      const Properties&       globdat );

  static void               declare               ();


 protected:

  virtual                  ~GmshInputModule       ();


 private:

  void                      initItemSets_         

    ( jive::util::StorageMode mode, 
      const Properties&       globdat );

  void                      readMesh_             

    ( const String&           fileName,
      const IntVector&        eGrpIdx, 
      const Properties&       globdat );

  void                      checkHighOrderMesh_   () const; 


 private:

  Assignable<XElementSet>   xelems_;
  Assignable<XNodeSet>      xnodes_;

  String                    fileName_;

  idx_t                     rank_;

};


#endif
