program = fe2 

include $(JEMDIR)/packages/mt/Makedefs.mk
include $(JIVEDIR)/makefiles/prog.mk
include $(JIVEDIR)/makefiles/packages/*.mk

MY_CXX_STD_FLAGS = -std=c++17 -Wno-unused-local-typedefs -Werror
